language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x

go_import_path: github.com/folivora-ice/rotinpo

script:
  - go vet .
  - go test -v .

notifications:
  email:
    recipients:
      - bin.zaq@foxmail.com
    on_success: never
    on_error: always
    on_failure: always
    on_start: never